name: バグレポート
description: NZEで発生した不具合のレポートを送信
title: "不具合のタイトル"
labels: ["bug"]
body:
  - type: dropdown
    id: version
    attributes:
      label: 不具合の種類
      options:
        - ゲームシステム
        - 武器，アイテム
        - マップ
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: 不具合の内容
      placeholder: 不具合が発生したときの状況や過程を具体的に記入してください。
    validations:
      required: true
  - type: textarea
    id: expect
    attributes:
      label: 期待される動作
      placeholder: 不具合が起きた事象は本来どのように動作するべきでしたか？
    validations:
      required: true
